### PR TITLE
Re add styles that was removed

### PR DESCRIPTION
**Pull request by sheela-svmx**
Styles were removed in this [PR](https://github.com/predixdesignsystem/px-dropdown/commit/37f3de3cfd5b63e014df1124b39af7d2cf9c7197#diff-d8ea3950d02747c8137e64a5bbb01a91L310) 

This was causing regression in  px-dropdown padding left when it was used in readOnly mode.

### CODE REVIEW

**Comment by sheela-svmx** [comment]
@joshsylvester @mallik Please help review

**Comment by sheela-svmx** [comment]
screen shot 2019-02-28 at 12 40 44 pm

**Comment by benjaminliugang** [comment]
If we add back these styles, we could close this [PR](https://github.com/predixdesignsystem/px-dropdown/pull/104), the item icon's margin-right value will be back.

**Comment by sheela-svmx** [comment]
@benjaminliugang  this PR, adds back a style that was removed so some trumps spacing styles were removed that, removes padding for px-dropdown of a certain style. BUt that PR https://github.com/predixdesignsystem/px-dropdown/pull/104/files is a different issue, its for RTL spacing so we need both

**Comment by sheela-svmx** [comment]
I am closing this PR since  https://github.com/predixdesignsystem/px-dropdown/pull/104 has both combined

**Pull request closed without merging**
