### PR TITLE
Reverse the dropdown items icon when the direction is RTL

### PR DESCRIPTION
**Pull request by benjaminliugang**
Reverse the dropdown items icon when the direction is RTL

### CODE REVIEW

**Comment by benjaminliugang** [comment]
@evanjd , please help review.

**Comment by evanjd** [comment]
@benjaminliugang Sorry, I don’t work at GE anymore.

**Comment by benjaminliugang** [comment]
@joshsylvester ，could you help me merge and release this fix?

**Comment by joshsylvester** [comment]
Merging with two approvals.

**Pull request merged**
