### PR TITLE
Removes ES6 functionality to support IE11

### PR DESCRIPTION
**Pull request by kdinluks**
No changes to actual functionality, only removes ES6 notations like const, let, =>, ..., in order to support IE11.

### CODE REVIEW

**Comment by mdwragg** [comment]
Hmmm, this strikes me as a bad idea. 5 dollar says there's ES6 in a dependency of one of these components. You can't rewrite those - how about using babel in your build chain instead?

**Comment by jimdefrisco** [comment]
Yeah, there are definitely es6 dependencies in other components. We added babel to accommodate those dependencies in the newest px-vis components for APM Analysis (though we still hit minor issues with some code not passing strict mode, which babel was enforcing). You are right, @mdwragg , this is not a good policy moving forward....thanks for weighing in.

**Comment by kdinluks** [comment]
@mdwragg Could you point me to where that would be a problem? I want to make sure I don't break anything.
But I don't see why moving to ES5 would be a problem, that's actually what babel does for you.

**Comment by mdwragg** [comment]
@kdinluks - there'll likely be ES6 inside a transitive dependency, you can't rewrite each dep as you don't have control over it.

Also, you're guessing what the unravelling of ES6 will look like in ES5 - that is risky!

Safest bet is to put babel into your build, assume the worst that a transitive dependency will contain ES5 and blow your code up at some point in the future.

**Pull request merged**
